<?xml version="1.0" encoding="utf-8"?><Database Name="Stelter-forms" Class="StelterFormsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=Stelter-forms;Persist Security Info=True;User ID=stelter" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Stelter_formsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FormSubmissions" Member="FormSubmissions">
    <Type Name="FormSubmission">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReferringUrl" Type="System.String" DbType="NChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NextPage" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NextPageLinkName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>